SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APEXSQL_BEFORE_AFTER_OPERATION] (
		[LSN]                [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DATABASE_ID]        [int] NOT NULL,
		[TIME]               [datetime] NULL,
		[OPERATION_TYPE]     [varchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[SCHEMA]             [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TABLE]              [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[USER_NAME]          [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DURATION]           [float] NULL,
		[RECONSTRUCTED]      [bit] NULL,
		CONSTRAINT [PK_APEXSQL_BEFORE_AFTER_OPERATION]
		PRIMARY KEY
		CLUSTERED
		([LSN], [DATABASE_ID])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APEXSQL_BEFORE_AFTER_OPERATION] SET (LOCK_ESCALATION = TABLE)
GO
