SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APEXSQL_BEFORE_AFTER_DATABASE] (
		[ID]           [int] NOT NULL,
		[SERVER]       [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DATABASE]     [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK__APEXSQL___3214EC27EC810916]
		PRIMARY KEY
		CLUSTERED
		([ID])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[APEXSQL_BEFORE_AFTER_DATABASE] SET (LOCK_ESCALATION = TABLE)
GO
