SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APEXSQL_BEFORE_AFTER_DETAIL] (
		[LSN]                [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DATABASE_ID]        [int] NOT NULL,
		[ROW_ORDINAL]        [smallint] NOT NULL,
		[LINE_NO]            [smallint] NOT NULL,
		[IS_PRIMARY_KEY]     [bit] NOT NULL,
		[COLUMN_NAME]        [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BEFORE]             [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AFTER]              [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK_APEXSQL_BEFORE_AFTER_DETAIL]
		PRIMARY KEY
		CLUSTERED
		([LSN], [DATABASE_ID], [ROW_ORDINAL], [LINE_NO], [IS_PRIMARY_KEY])
	ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[APEXSQL_BEFORE_AFTER_DETAIL] SET (LOCK_ESCALATION = TABLE)
GO
